server:
  port: 8001

mybatis:
  #mybatis配置文件路径
  config-location: classpath:mybatis/mybatis-cfg.xml
  #Entity别名类路径
  type-aliases-package: com.arch.springcloud.entities
  #mapper映射文件路径
  mapper-locations: classpath:mybatis/mapper/**/*.xml

spring:
  application:
    name: microservicecloud-dept        #微服务名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB01              # 数据库名称
    username: root
    password: mysql
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200
      test-while-idle: true
      validation-query: SELECT 1 FROM DUAL

##############客户端注册进eureka服务列表
eureka:
  client:
    service-url:
      #将微服务注册到台eureka集群中
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:     #主机名称:服务名称修改
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true #访问路径可以显示IP地址

###########为eureka中点击服务添加info信息 http://192.168.28.1:8001/info
info:
  app.name: atguigu-microservicecloud
  company.name: www.arch.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
