server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

zuul:
  routes:
    #配置路由访问映射规则
    #未配置之前：http://myzuul.com:9527/microservicecloud-dept/dept/get/2
    #配置之后：http://myzuul.com:9527/mydept/dept/get/1
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
  #忽略未配置之前的访问url：ttp://myzuul.com:9527/microservicecloud-dept/dept/get/2，此时将无法访问
  #忽略多个时可用"*"来实现
  ignored-services: "*"   #microservicecloud-dept
  #设置公共访问路径前缀
  #http://myzuul.com:9527/arch/mydept/dept/get/1
  prefix: /arch


info:
  app.name: atguigu-microcloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
